import 'package:tmtdslt/layout/flexible_layout/theme/flex_theme.dart';

/// CSS styles for FlexibleLayout
///
/// Extracted from flex_layout.dart to keep the main file clean.
/// This file contains all the CSS styling for the Donovan theme layout.

String get flexLayoutStyles =>
    '''
  /* ========================================
     NOTE: CSS Variables are now generated by FlexTheme.generateThemeCSS()
     See lib/layout/flexible_layout/flex_theme.dart for color definitions
     ======================================== */

  /* ========================================
     BASE LAYOUT
     ======================================== */

  .flex-layout {
    min-height: 100vh;
    display: flex;
    flex-direction: column;
    background-color: var(--page-bg);
    color: var(--text-color);
    font-family: var(--font-body);
    font-size: var(--font-size-base);
    line-height: var(--line-height-body);
  }

  /* ========================================
     HEADER
     ======================================== */

  .flex-header {
    background-color: var(--content-bg);
  }

  .flex-header-content {
    max-width: 100%;
    padding: var(--spacing-lg) var(--content-padding);
    display: flex;
    justify-content: space-between;
    align-items: center;
    flex-wrap: wrap;
    gap: var(--spacing-md);
  }

  .flex-site-branding {
    flex: 1;
    min-width: var(--sidebar-width);
  }

  .flex-site-title {
    margin: 0;
    font-size: var(--font-size-h2);
    font-family: var(--font-title);
    font-weight: 700;
    line-height: var(--line-height-heading);
  }

  .flex-site-title a {
    color: var(--text-color);
    text-decoration: none;
    transition: color 0.2s ease;
  }

  .flex-site-title a:hover {
    color: var(--link-color);
  }

  .flex-site-tagline {
    margin: var(--spacing-xs) 0 0 0;
    color: var(--text-muted);
    font-size: var(--font-size-small);
    font-style: italic;
  }

  /* Header actions (social media + theme toggle) */
  .flex-header-actions {
    display: flex;
    align-items: center;
    gap: var(--spacing-lg);
    flex-shrink: 0;
  }

  /* Social media icons in header */
  .flex-social-nav {
    flex-shrink: 0;
  }

  .flex-social-menu {
    list-style: none;
    margin: 0;
    padding: 0;
    display: flex;
    gap: var(--spacing-md);
  }

  .flex-social-menu li {
    margin: 0;
  }

  .flex-social-menu a {
    display: block;
    font-size: var(--font-size-h3);
    color: var(--text-color);
    text-decoration: none;
    transition: transform var(--transition-duration) ease;
  }

  .flex-social-menu a:hover {
    transform: scale(1.2);
  }

  /* Menu bar */
  .flex-menu-bar {
    background-color: var(--navi-background);
    position: relative;
  }

  /* Hamburger menu toggle (mobile only) */
  .flex-menu-toggle {
    display: none;
    background: none;
    border: none;
    padding: var(--spacing-md);
    cursor: pointer;
    color: white;
  }

  .hamburger {
    display: block;
    width: var(--hamburger-width);
    height: var(--hamburger-height);
    background-color: white;
    position: relative;
  }

  .hamburger::before,
  .hamburger::after {
    content: '';
    display: block;
    width: var(--hamburger-width);
    height: var(--hamburger-height);
    background-color: white;
    position: absolute;
    left: 0;
  }

  .hamburger::before {
    top: calc(-1 * var(--hamburger-spacing));
  }

  .hamburger::after {
    top: var(--hamburger-spacing);
  }

  /* Category navigation */
  .flex-nav {
    padding: 0 var(--content-padding);
  }

  .flex-category-menu {
    list-style: none;
    margin: 0;
    padding: 0;
    display: flex;
    flex-wrap: wrap;
    gap: 0;
  }

  .flex-category-menu li {
    margin: 0;
  }

  .flex-category-menu a {
    display: block;
    padding: var(--spacing-md) var(--spacing-lg);
    color: white;
    text-decoration: none;
    font-weight: 500;
    transition: background-color 0.2s ease;
    white-space: nowrap;
  }

  .flex-category-menu a:hover {
    background-color: var(--navi-hover);
  }

  .flex-category-menu a.active {
    background-color: var(--navi-active);
    font-weight: 600;
  }

  /* Content wrapper */
  .flex-content-wrapper {
    flex: 1;
    padding: var(--content-padding);
    width: 100%;
    box-sizing: border-box;
    display: flex;
    gap: var(--spacing-lg);
    align-items: start;
  }

  /* Main content - grows to fill available space */
  .flex-main {
    background-color: transparent;
    padding: 0;
    flex-grow: 1;
    flex-shrink: 1;
    flex-basis: 0;
    min-width: 0;
    max-width: 100%;
    overflow-wrap: break-word;
    word-wrap: break-word;
    word-break: break-word;
  }

  /* Ensure all content inside wraps properly */
  .flex-main * {
    max-width: 100%;
    box-sizing: border-box;
  }

  .flex-main img {
    height: auto;
  }

  .flex-main pre,
  .flex-main code {
    overflow-x: auto;
    white-space: pre-wrap;
    word-wrap: break-word;
  }

  /* Sidebar - transparent background, container for widgets */
  .flex-sidebar {
    background-color: transparent;
    padding: 0;
    width: var(--sidebar-width);
    flex: 0 0 var(--sidebar-width);
    position: sticky;
    top: var(--spacing-md);
    display: flex;
    flex-direction: column;
    gap: var(--spacing-md);
  }

  /* Individual sidebar widgets - each in its own box */
  .flex-widget {
    background-color: var(--content-bg);
    padding: var(--spacing-md);
    border-radius: var(--border-radius);
    box-shadow: var(--box-shadow) var(--post-line);
  }

  .flex-widget h3 {
    margin-top: 0;
    margin-bottom: var(--spacing-sm);
    font-size: var(--font-size-h4);
    color: var(--text-color);
    padding-bottom: var(--spacing-xs);
  }

  /* Sidebar widget with horizontal line under title */
  .sidebar-widget-with-line h3 {
    border-bottom: var(--sidebar-widget-border-width) var(--sidebar-widget-border-style) var(--sidebar-widget-border-color);
  }

  .flex-widget ul {
    list-style: none;
    padding: 0;
    margin: 0;
  }

  .flex-widget li {
    margin-bottom: var(--spacing-xs);
  }

  .flex-widget a {
    color: var(--link-color);
    text-decoration: none;
  }

  .flex-widget a:hover {
    color: var(--link-hover-color);
  }

  /* Recent Posts widget - specific styling */
  .flex-recent-posts ul {
    list-style: none;
    padding: 0;
    margin: 0;
  }

  .flex-recent-posts li {
    margin-bottom: var(--spacing-sm);
    line-height: 1.4;
  }

  .flex-recent-posts a {
    color: var(--sidebar-recent-posts);
    text-decoration: none;
    transition: color 0.2s ease;
  }

  .flex-recent-posts a:hover {
    color: var(--sidebar-recent-posts);
    text-decoration: underline;
    text-decoration-color: var(--sidebar-recent-posts-underline);
  }

  /* Dropdown select styling (unified for all dropdown types) */
  .dropdown-select,
  .archive-dropdown,
  .tag-dropdown,
  .category-dropdown {
    width: 100%;
    padding: var(--spacing-xs);
    padding-right: 2em;
    border: var(--border-width-thin) solid var(--border-color);
    border-radius: var(--border-radius-sm);
    background-color: var(--content-bg);
    background-image: var(--dropdown-arrow-icon);
    background-repeat: no-repeat;
    background-position: right 0.5em center;
    background-size: 1.2em;
    color: var(--text-color);
    font-family: var(--font-body);
    font-size: var(--font-size-small);
    line-height: 1.5;
    cursor: pointer;
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
  }

  /* Dropdown sidebar widget container (unified for all dropdown types) */
  .dropdown-sidebar,
  .flex-archive,
  .flex-tag-dropdown,
  .flex-category-dropdown {
    /* Inherits from .flex-widget */
  }

  /* Tag Cloud widget - dyslexia-friendly spacing */
  .flex-tag-cloud h3 a {
    color: inherit;
    text-decoration: none;
  }

  .flex-tag-cloud h3 a:hover {
    color: var(--link-color);
    text-decoration: underline;
  }

  .tag-cloud-content {
    display: flex;
    flex-wrap: wrap;
    gap: 12px 16px;
    line-height: 1;
  }

  .tag-cloud-content a {
    color: var(--sidebar-recent-posts);
    text-decoration: none;
    transition: color 0.2s ease;
  }

  .tag-cloud-content a:hover {
    color: var(--sidebar-recent-posts);
    text-decoration: underline;
    text-decoration-color: var(--sidebar-recent-posts-underline);
  }

  /* Dropdown inline mode (inside post header on archive/tag/category pages) - UNIFIED */
  .dropdown-inline,
  .tag-selector-inline,
  .archive-selector-inline,
  .category-selector-inline {
    display: flex;
    align-items: center;
    gap: var(--spacing-sm);
  }

  .dropdown-inline .dropdown-label,
  .tag-selector-inline .tag-label,
  .archive-selector-inline .archive-label,
  .category-selector-inline .category-label {
    font-family: var(--font-title);
    font-size: var(--font-size-post-title);
    font-weight: var(--font-weight-post-title);
    color: var(--text-color);
    white-space: nowrap;
  }

  .dropdown-inline select,
  .tag-selector-inline select,
  .archive-selector-inline select,
  .category-selector-inline select {
    flex: 1;
    max-width: 400px;
    padding: var(--spacing-xs);
    padding-right: 2em;
    border: var(--border-width-thin) solid var(--border-color);
    border-radius: var(--border-radius-sm);
    background-color: var(--content-bg);
    background-image: var(--dropdown-arrow-icon);
    background-repeat: no-repeat;
    background-position: right 0.5em center;
    background-size: 1.5em;
    color: var(--text-color);
    font-family: var(--font-title);
    font-size: var(--font-size-post-title);
    font-weight: var(--font-weight-post-title);
    cursor: pointer;
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
  }

  /* Mobile: Stack sidebar below content */
  @media screen and (max-width: ${FlexTheme.breakpointMobile}px) {
    .flex-content-wrapper {
      flex-direction: column;
    }

    .flex-sidebar {
      width: 100%;
      position: static;
    }
  }

  /* ========================================
     POST HEADER STYLES
     ======================================== */

  .flex-post-header {
    background: var(--content-bg);
    padding: var(--spacing-sm);
    margin-bottom: var(--spacing-lg);
    border-radius: var(--border-radius);
  }

  /* Post title at top */
  .flex-post-title {
    color: var(--text-color);
    font-family: var(--font-title);
    font-size: var(--font-size-post-title) !important;
    font-weight: var(--font-weight-post-title) !important;
    line-height: var(--line-height-heading);
    margin: 0 !important;
    padding: 0 !important;
  }

  /* Post metadata below title (date and author) */
  .flex-post-meta {
    display: flex;
    gap: 0;
    flex-wrap: wrap;
    color: var(--text-muted);
    font-size: var(--font-size-sm);
    margin: 0;
  }

  /* Only add top margin to post-meta if it has content */
  .flex-post-meta:not(:empty) {
    margin-top: var(--spacing-sm);
  }

  .flex-post-date,
  .flex-post-author {
    display: inline-block;
  }

  .flex-post-author::before {
    content: ' ';
    margin-right: var(--spacing-sm);
  }

  /* Featured image below post metadata */
  .flex-featured-image {
    margin-bottom: var(--spacing-xl);
  }

  .flex-featured-image img {
    width: 100%;
    height: auto;
    border-radius: var(--border-radius);
    display: block;
  }

  /* ========================================
     MARKDOWN CONTENT STYLES
     ======================================== */

  /* Headings */
  .flex-main h1,
  .flex-main h2,
  .flex-main h3,
  .flex-main h4,
  .flex-main h5,
  .flex-main h6 {
    color: var(--text-color);
    font-family: var(--font-title);
    line-height: var(--line-height-heading);
    margin-top: var(--spacing-xl);
    margin-bottom: var(--spacing-md);
    font-weight: 600;
  }

  .flex-main h1 { font-size: var(--font-size-h1); margin-top: 0; }
  .flex-main h2 { font-size: var(--font-size-h2); }
  .flex-main h3 { font-size: var(--font-size-h3); }
  .flex-main h4 { font-size: var(--font-size-h4); }

  /* Paragraphs */
  .flex-main p {
    color: var(--text-color);
    margin-bottom: var(--spacing-md);
    line-height: var(--line-height-body);
  }

  /* Links */
  .flex-main a {
    color: var(--link-color);
    text-decoration: none;
    border-bottom: var(--border-width-thin) solid transparent;
    transition: all var(--transition-duration) ease;
  }

  .flex-main a:hover {
    color: var(--link-hover);
    border-bottom-color: var(--link-hover);
  }

  /* Post card links - no border-bottom underlines, only color change on hover */
  .post-card a {
    border-bottom: none !important;
  }

  /* Lists */
  .flex-main ul,
  .flex-main ol {
    color: var(--text-color);
    margin-bottom: var(--spacing-md);
    padding-left: var(--spacing-xl);
  }

  .flex-main li {
    margin-bottom: var(--spacing-sm);
  }

  /* Strong/Bold */
  .flex-main strong {
    color: var(--text-color);
    font-weight: 600;
  }

  /* Horizontal rule */
  .flex-main hr {
    border: none;
    border-top: var(--border-width-thin) solid var(--border-color);
    margin: var(--spacing-xl) 0;
  }

  /* Code */
  .flex-main code {
    background-color: var(--border-color);
    color: var(--text-color);
    padding: var(--spacing-xs) var(--spacing-sm);
    border-radius: var(--border-radius-sm);
    font-size: 0.9em; /* em unit intentionally relative to parent font size */
  }

  /* Blockquotes */
  .flex-main blockquote {
    border-left: var(--border-width-thick) solid var(--link-color);
    padding-left: var(--spacing-lg);
    margin: var(--spacing-lg) 0;
    color: var(--text-muted);
    font-style: italic;
  }

  /* ========================================
     BLOG POST STYLING (DONOVAN THEME)
     ======================================== */

  /* Styling - Post page styling for individual blog posts */
  main.post-page{
    background-color: var(--content-bg);
    border-radius: var(--border-radius);
    padding: var(--spacing-lg);
  }

  /* Styling - for static pages */
  main.static-page{
    background-color: var(--content-bg);
    border-radius: var(--border-radius);
    padding: var(--spacing-lg);
  }

  /* Archive and page styling - transparent background, content has white boxes */
  /* main.archive-page and main.page-page use default styling */
  /* main.home-page also uses default styling */

  /* Post meta (date and author) */
  .flex-main .entry-meta {
    color: var(--text-muted);
    font-size: var(--font-size-small);
    margin-bottom: var(--spacing-lg);
  }

  /* Other images (not first, not signature) - default styling */
  .flex-main img {
    max-width: 100%;
    height: auto;
    margin: var(--spacing-md) 0;
  }

  /* WordPress alignment classes - alignleft */
  .flex-main .alignleft,
  .flex-main img.alignleft {
    float: left;
    margin: 0 var(--spacing-lg) var(--spacing-lg) 0;
    max-width: var(--content-image-max-width);
  }

  .flex-main .alignleft img {
    max-width: 100%;
    width: auto;
    height: auto;
    margin: 0;
  }

  /* WordPress alignment classes - alignright */
  .flex-main .alignright,
  .flex-main img.alignright {
    float: right;
    margin: 0 0 var(--spacing-lg) var(--spacing-lg);
    max-width: var(--content-image-max-width);
  }

  .flex-main .alignright img {
    max-width: 100%;
    width: auto;
    height: auto;
    margin: 0;
  }

  /* WordPress alignment classes - aligncenter */
  .flex-main .aligncenter,
  .flex-main img.aligncenter {
    display: block;
    margin: var(--spacing-lg) auto;
    max-width: 100%;
  }

  .flex-main .aligncenter img {
    max-width: 100%;
    height: auto;
    margin: 0;
  }

  /* First image or first figure floats left with text wrapping (fallback for images without alignment class) */
  .flex-main > section > img:first-child:not(.alignright):not(.aligncenter):not([alt*="signature"]):not([src*="signature"]),
  .flex-main > section > figure.image:first-child:not(.alignright):not(.aligncenter),
  .flex-main > section > figure.image:first-child:not(.alignright):not(.aligncenter) img:not([alt*="signature"]):not([src*="signature"]),
  .flex-main > section > p:first-child img:first-child:not(.alignright):not(.aligncenter):not([alt*="signature"]):not([src*="signature"]) {
    float: left;
    margin: 0 var(--spacing-lg) var(--spacing-lg) 0;
    max-width: var(--content-image-max-width);
    width: auto;
    height: auto;
  }

  /* Signature image - left aligned (like signing a letter) */
  .flex-main img[alt*="signature"],
  .flex-main img[alt*="Signature"],
  .flex-main img[src*="signature"],
  .flex-main img[src*="Signature"] {
    float: none !important;
    display: block;
    margin: 0 auto 0 0;
    max-width: var(--signature-image-max-width);
  }

  /* Remove extra spacing from paragraph/figure containing signature */
  .flex-main p:has(img[alt*="signature"]),
  .flex-main p:has(img[alt*="Signature"]),
  .flex-main p:has(img[src*="signature"]),
  .flex-main p:has(img[src*="Signature"]),
  .flex-main figure:has(img[alt*="signature"]),
  .flex-main figure:has(img[alt*="Signature"]),
  .flex-main figure:has(img[src*="signature"]),
  .flex-main figure:has(img[src*="Signature"]) {
    margin: 0;
    padding: 0;
  }

  /* ========================================
     POST FOOTER (CATEGORIES & TAGS)
     ======================================== */

  .flex-post-footer {
    clear: both;
    margin-top: var(--spacing-xl);
    padding-top: var(--spacing-md);
  }

  .flex-post-footer hr {
    border: none;
    border-top: var(--border-width-thin) solid var(--border-color);
    margin: 0 0 var(--spacing-md) 0;
  }

  .flex-post-categories,
  .flex-post-tags {
    display: flex;
    align-items: center;
    gap: 0;
    margin-bottom: var(--spacing-sm);
    font-size: var(--font-size-sm);
    color: var(--text-muted);
  }

  .flex-category-icon,
  .flex-tag-icon {
    font-size: 1.1em; /* em unit intentionally relative to parent font size */
    margin-right: var(--spacing-xs);
  }

  .flex-post-categories a,
  .flex-post-tags a {
    color: var(--post-category);
    text-decoration: none;
    border-bottom: none !important;
    transition: color 0.2s ease;
  }

  .flex-post-categories a:hover,
  .flex-post-tags a:hover {
    color: var(--post-category-hover) !important;
  }

  /* ========================================
     POST NAVIGATION (PREVIOUS/NEXT LINKS)
     ======================================== */

  .post-navigation {
    margin-top: var(--spacing-xl);
    padding-top: var(--spacing-lg);
    border-top: var(--border-width-thin) solid var(--border-color);
    display: flex;
    justify-content: space-between;
    gap: var(--spacing-md);
  }

  .nav-previous,
  .nav-next {
    flex: 1;
    max-width: 48%;
  }

  .nav-previous {
    text-align: left;
  }

  .nav-next {
    text-align: right;
  }

  .post-navigation a {
    color: var(--link-color);
    text-decoration: none;
    display: inline-block;
    transition: color 0.2s ease;
  }

  .post-navigation a:hover {
    color: var(--link-hover);
  }

  .nav-arrow {
    font-weight: bold;
    font-size: 1.2em; /* em unit intentionally relative to parent font size */
  }

  .nav-label {
    font-size: var(--font-size-sm);
    color: var(--text-muted);
    font-weight: normal;
  }

  .nav-title {
    display: block;
    margin-top: var(--spacing-xs);
    font-weight: 600;
    color: var(--link-color);
  }

  .post-navigation a:hover .nav-title {
    color: var(--link-hover);
  }

  /* ========================================
     FOOTER
     ======================================== */

  .flex-footer {
    background-color: var(--content-bg);
    border-top: var(--border-width-thin) solid var(--border-color);
    padding: var(--spacing-lg) 0;
    margin-top: var(--spacing-xl);
  }

  .flex-footer-content {
    max-width: 100%;
    padding: 0 var(--content-padding);
    display: flex;
    justify-content: space-between;
    align-items: center;
    flex-wrap: wrap;
    gap: var(--spacing-md);
  }

  .flex-copyright {
    margin: 0;
    color: var(--text-muted);
    font-size: var(--font-size-small);
  }

  .flex-jaspr-badge {
    display: flex;
    align-items: center;
  }

  /* Show light badge in light mode, dark badge in dark mode */
  .jaspr-badge-light {
    display: flex;
  }

  .jaspr-badge-dark {
    display: none;
  }

  @media (prefers-color-scheme: dark) {
    .jaspr-badge-light {
      display: none;
    }

    .jaspr-badge-dark {
      display: flex;
    }
  }

  /* ========================================
     MOBILE RESPONSIVE
     ======================================== */

  @media screen and (max-width: ${FlexTheme.breakpointMobile}px) {
    /* Header stacks on mobile */
    .flex-header-content {
      flex-direction: column;
      align-items: flex-start;
    }

    /* Social icons stay horizontal on mobile */
    .flex-social-nav {
      width: 100%;
    }

    .flex-social-menu {
      justify-content: flex-start;
    }

    /* Show hamburger menu */
    .flex-menu-toggle {
      display: block;
    }

    /* Hide navigation by default on mobile */
    .flex-nav {
      display: none;
      flex-direction: column;
      padding: 0;
    }

    /* Show navigation when menu is open */
    .flex-menu-bar.menu-open .flex-nav {
      display: flex;
    }

    .flex-category-menu {
      flex-direction: column;
      width: 100%;
    }

    .flex-category-menu a {
      padding: var(--spacing-md) var(--content-padding);
      border-bottom: var(--border-width-thin) solid var(--navi-hover);
    }

    .flex-content-wrapper {
      flex-direction: column;
    }

    .flex-sidebar {
      width: 100%;
      position: static;
    }

    .flex-footer-content {
      flex-direction: column;
      align-items: center;
      text-align: center;
      gap: var(--spacing-md);
    }

    .posts-grid {
      grid-template-columns: 1fr;
    }
  }

  /* ========================================
     POSTS GRID COMPONENT
     ======================================== */

  .posts-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(var(--posts-grid-min-width), 1fr));
    gap: var(--spacing-lg);
    margin: 0 0 var(--spacing-lg);
    max-width: 100%;
  }

  .posts-grid-empty {
    text-align: center;
    padding: var(--spacing-2xl);
    color: var(--text-muted);
  }

  .post-card {
    margin: 0;
    padding: var(--spacing-lg);
    background: var(--content-bg);
    border-radius: var(--border-radius);
    box-shadow: var(--box-shadow) var(--post-line);
    min-width: 0;
    word-wrap: break-word;
  }

  .post-card-image-link {
    display: block;
    margin-bottom: 1em; /* em unit intentionally relative to font size for proportional spacing */
  }

  .post-card-image {
    width: var(--post-card-image-size);
    height: var(--post-card-image-size);
    object-fit: cover;
    vertical-align: top;
  }

  .post-card-content {
    /* Content flows naturally */
  }

  .post-card-title {
    margin-top: 0;
    margin-bottom: 0.2em; /* em unit intentionally relative to font size for proportional spacing */
    padding: 0;
    font-size: var(--font-size-h4);
    font-weight: normal;
    line-height: 1.4;
  }

  .post-card-title a {
    color: var(--post-title);
    text-decoration: none;
  }

  .post-card-title a:hover {
    color: var(--post-title);
    text-decoration: none;
  }

  .post-card-meta {
    margin: 0 0 0.5em; /* em unit intentionally relative to font size for proportional spacing */
    font-size: var(--font-size-small);
    color: var(--text-muted);
  }

  .post-card-excerpt {
    margin: 0;
    line-height: 1.6;
  }

  .post-card-excerpt p:last-child {
    margin-bottom: 0;
  }

  .post-card-taxonomy {
    display: flex;
    flex-direction: column;
    gap: var(--spacing-xs);
    font-size: var(--font-size-small);
    margin-top: 1em; /* em unit intentionally relative to font size for proportional spacing */
    padding-top: 1em; /* em unit intentionally relative to font size for proportional spacing */
    border-top: var(--border-width-thin) solid var(--post-line);
  }

  .post-card-categories,
  .post-card-tags {
    display: flex;
    flex-wrap: wrap;
    align-items: baseline;
    line-height: 1.6;
  }

  .post-card-categories a,
  .post-card-tags a {
    color: var(--post-category);
    text-decoration: none;
  }

  .post-card-categories a:hover,
  .post-card-tags a:hover {
    color: var(--post-category-hover);
    text-decoration: none;
  }

  .taxonomy-icon {
    margin-right: 0.25em; /* em unit intentionally relative to font size for proportional spacing */
  }

  .post-card-button {
    display: inline-block;
    padding: var(--spacing-sm) var(--spacing-lg);
    background: var(--post-button-background);
    color: var(--post-button-text);
    text-decoration: none;
    border-radius: var(--border-radius-sm);
    text-align: center;
    transition: background var(--transition-duration) ease;
    align-self: flex-start;
    font-size: var(--font-size-small);
  }

  .post-card-button:hover {
    background: var(--post-button-background-hover);
    color: var(--post-button-text-hover) !important;
    text-decoration: none;
  }

  /* ========================================
     PAGINATION STYLES
     ======================================== */

  .pagination {
    margin-top: var(--spacing-xl);
    margin-bottom: var(--spacing-xl);
  }

  .pagination-links {
    display: flex;
    justify-content: flex-start;
    align-items: center;
    gap: var(--spacing-xs);
    flex-wrap: wrap;
  }

  .pagination-previous,
  .pagination-next,
  .pagination-number,
  .pagination-current,
  .pagination-ellipsis {
    display: inline-block;
    padding: var(--spacing-xs) var(--spacing-sm);
    min-width: 2.5rem;
    text-align: center;
    text-decoration: none;
    border-radius: var(--border-radius-sm);
    font-size: var(--font-size-small);
    line-height: 1.4;
  }

  /* Clickable pagination links */
  .pagination-previous,
  .pagination-next,
  .pagination-number {
    background: var(--post-button-background);
    color: var(--post-button-text);
    text-decoration: none !important;
    border-bottom: none !important;
    transition: background var(--transition-duration) ease;
  }

  .pagination-previous:hover,
  .pagination-next:hover,
  .pagination-number:hover {
    background: var(--post-button-background-hover);
    color: var(--post-button-text-hover) !important;
    text-decoration: none !important;
    border-bottom: none !important;
  }

  /* Current page (not clickable) */
  .pagination-current {
    background: var(--post-button-background-hover);
    color: var(--post-button-text-hover);
    font-weight: 600;
  }

  /* Ellipsis */
  .pagination-ellipsis {
    background: transparent;
    color: var(--text-muted);
    padding: var(--spacing-xs);
    min-width: auto;
  }

  /* Previous/Next links - slightly wider */
  .pagination-previous,
  .pagination-next {
    min-width: auto;
    padding: var(--spacing-xs) var(--spacing-md);
  }

''';
